Ext.define('Traccar.view.deviceOverview.DevicesView', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Traccar.view.deviceOverview.DeviceOverviewStore',
        'Traccar.view.deviceOverview.OverviewController',
        'Traccar.view.deviceOverview.DeviceViewConfigController'
    ],

    controller: 'overview',

    floating: true,
    shadow: false,
    border: false,
    frame: false,
    height: Ext.getBody().getViewSize().height,
    width: 300,
    bodyStyle: 'background:transparent;',
    layout: 'fit',
    margin: '10px 10px 10px 10px',
    scrollable: 'y',

    items:[{
        xtype: 'dataview',
        listeners:{
            itemclick:'onStateItemClick'
        },
        tpl: new Ext.XTemplate('<tpl for=".">',
            '<div style="margin:10px;background-color:lightgrey;border-radius:15px" height= "50 px" class="thumb-wrap">',
                '<div style="background-color:seagreen;font-weight:bold;padding:6px;border-top-left-radius: 15px;border-top-right-radius:15px;">{name}</div>',
                '<div style="padding:5px;">',
                    '<table width="100%" style="border-spacing:5px;">',
                        '<tr style="cursor:pointer;">',
                            '<td {speed} width="20%" style="font-weight:bold;text-align:center;margin:8px;padding:4px;background-color:white;border-radius:8px;">',
                                '<img src="./images/speed.svg" width="20" height="20">',
                                '<br/><tpl if="state && state.speed">',
                                        '{state.speed}',
                                      '<tpl else>',
                                          'N/A',
                                      '</tpl>',
                            '</td>',
                            '<td {battery} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<img src="./images/1.gif" width="20" height="20">',
                                '<br/><tpl if="state && state.attributes && state.attributes.batteryLevel">',
                                    '{state.attributes.batteryLevel}V',
                                '<tpl else>',
                                    'N/A',
                                '</tpl>',
                            '</td>',
                            '<td {ignition} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<tpl if="state && state.attributes && state.attributes.ignition">',
                                    '<img src="./images/2.gif" width="30" height="30">',
                                '<tpl else>',
                                    '<img src="./images/2.gif" width="30" height="30">',
                                '</tpl>',
                            '</td>',
                            '<td {temp} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<img src="./images/3.png" width="20" height="20">',
                                '<br/><tpl if="state && state.attributes && state.attributes.temp0">',
                                    '{state.attributes.temp0}',
                                '<tpl else>',
                                    'N/A',
                                '</tpl>',
                            '</td>',
                            '<td {airConditioner} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<br/><tpl if="state && state.attributes && state.attributes.status">',
                                    '<img src="./images/5.png" width="30" height="30">',
                                '<tpl else>',
                                    '<img src="./images/air1.png" width="30" height="30">',
                                '</tpl>',
                            '</td>',
                            '<td {fuel} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<img src="./images/4.png" width="20" height="20">',
                                '<br/><tpl if="state && state.attributes && state.attributes.fuel">',
                                    '{state.attributes.fuel}',
                                '<tpl else>',
                                    'N/A',
                                '</tpl>',
                            '</td>',
                            '<td {coolantTemp} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<img src="./images/hot-water.svg" width="20" height="20">',
                                '<br/><tpl if="state && state.attributes && state.attributes.coolantTemp">',
                                    '{state.attributes.coolantTemp}',
                                '<tpl else>',
                                    'N/A',
                                '</tpl>',
                            '</td>',
                            '<td {rpm} width="20%" style="font-weight:bold;text-align:center;margin:8px;background-color:white;border-radius:8px;">',
                                '<img src="./images/1111.svg" width="20" height="20">',
                                '<br/><tpl if="state && state.attributes && state.attributes.rpm">',
                                    '{state.attributes.rpm}',
                                '<tpl else>',
                                    'N/A',
                                '</tpl>',
                            '</td>',
                        '</tr>',
                    '</table>',
                '</div>',
            '</div>',
         '</tpl>'),
        itemSelector: 'div.thumb-wrap'
    }],

    listeners: {
        addDevice: 'onAddDevice',
        removeDevice: 'onRemoveDevice'
    }
});
